# Generated by Django 4.0.2 on 2022-04-17 11:45

import classroom.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
        ('classroom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('marks', models.IntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.classroom')),
            ],
        ),
        migrations.AlterModelOptions(
            name='classstream',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='streamcomment',
            options={'ordering': ['time']},
        ),
        migrations.CreateModel(
            name='StudentWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.FileField(upload_to=classroom.models.upload_path_handler)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='classroom.assignment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.student')),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
    ]
