# Generated by Django 4.0.2 on 2022-04-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0002_assignment_alter_classstream_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classCode',
            field=models.CharField(editable=False, max_length=6, unique=True),
        ),
    ]
