# Generated by Django 4.0.2 on 2022-04-17 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_alter_classroom_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='className',
            field=models.CharField(max_length=100, unique=True, verbose_name='Name'),
        ),
    ]
