# Generated by Django 4.0.2 on 2022-04-21 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_assignment_description_alter_classteachers_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['-deadline']},
        ),
    ]
