# Generated by Django 4.0.2 on 2022-04-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0007_alter_classteachers_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'ordering': ['deadline']},
        ),
        migrations.AddField(
            model_name='studentwork',
            name='plagCheck',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
