# Generated by Django 4.0.2 on 2022-05-08 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_links_links_url'),
        ('classroom', '0008_alter_assignment_options_studentwork_plagcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentwork',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classroom.assignment'),
        ),
        migrations.AlterField(
            model_name='studentwork',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student'),
        ),
    ]
