# Generated by Django 4.0.2 on 2022-04-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_student_photo_links'),
    ]

    operations = [
        migrations.RenameField(
            model_name='links',
            old_name='links',
            new_name='url',
        ),
    ]
