# Generated by Django 4.0.2 on 2022-05-08 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_links_links_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='student/picture1.jpg', null=True, upload_to='student/'),
        ),
    ]
