# Generated by Django 4.0.2 on 2022-05-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, default='student/spidy2.png', null=True, upload_to='student/'),
        ),
    ]
